name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'

    - name: Build and Test
      run: |
        xcodebuild build-for-testing test \
          -scheme YourSchemeName \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          -enableCodeCoverage YES
