version: "3.8"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - ./app/node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped

