// Mocks generated by Mockito 5.4.6 from annotations
// in family_expense_tracker/test/mock/google_sheets_service_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:family_expense_tracker/data/models/expense_record.dart' as _i6;
import 'package:family_expense_tracker/services/google_sheets_service.dart'
    as _i3;
import 'package:googleapis/shared.dart' as _i7;
import 'package:googleapis/sheets/v4.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSpreadsheetsResource_0 extends _i1.SmartFake
    implements _i2.SpreadsheetsResource {
  _FakeSpreadsheetsResource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSpreadsheetsDeveloperMetadataResource_1 extends _i1.SmartFake
    implements _i2.SpreadsheetsDeveloperMetadataResource {
  _FakeSpreadsheetsDeveloperMetadataResource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeSpreadsheetsSheetsResource_2 extends _i1.SmartFake
    implements _i2.SpreadsheetsSheetsResource {
  _FakeSpreadsheetsSheetsResource_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSpreadsheetsValuesResource_3 extends _i1.SmartFake
    implements _i2.SpreadsheetsValuesResource {
  _FakeSpreadsheetsValuesResource_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatchUpdateSpreadsheetResponse_4 extends _i1.SmartFake
    implements _i2.BatchUpdateSpreadsheetResponse {
  _FakeBatchUpdateSpreadsheetResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeSpreadsheet_5 extends _i1.SmartFake implements _i2.Spreadsheet {
  _FakeSpreadsheet_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppendValuesResponse_6 extends _i1.SmartFake
    implements _i2.AppendValuesResponse {
  _FakeAppendValuesResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatchClearValuesResponse_7 extends _i1.SmartFake
    implements _i2.BatchClearValuesResponse {
  _FakeBatchClearValuesResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatchClearValuesByDataFilterResponse_8 extends _i1.SmartFake
    implements _i2.BatchClearValuesByDataFilterResponse {
  _FakeBatchClearValuesByDataFilterResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeBatchGetValuesResponse_9 extends _i1.SmartFake
    implements _i2.BatchGetValuesResponse {
  _FakeBatchGetValuesResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatchGetValuesByDataFilterResponse_10 extends _i1.SmartFake
    implements _i2.BatchGetValuesByDataFilterResponse {
  _FakeBatchGetValuesByDataFilterResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeBatchUpdateValuesResponse_11 extends _i1.SmartFake
    implements _i2.BatchUpdateValuesResponse {
  _FakeBatchUpdateValuesResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatchUpdateValuesByDataFilterResponse_12 extends _i1.SmartFake
    implements _i2.BatchUpdateValuesByDataFilterResponse {
  _FakeBatchUpdateValuesByDataFilterResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeClearValuesResponse_13 extends _i1.SmartFake
    implements _i2.ClearValuesResponse {
  _FakeClearValuesResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueRange_14 extends _i1.SmartFake implements _i2.ValueRange {
  _FakeValueRange_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateValuesResponse_15 extends _i1.SmartFake
    implements _i2.UpdateValuesResponse {
  _FakeUpdateValuesResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GoogleSheetsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSheetsService extends _i1.Mock
    implements _i3.GoogleSheetsService {
  MockGoogleSheetsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get spreadsheetId =>
      (super.noSuchMethod(
            Invocation.getter(#spreadsheetId),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#spreadsheetId),
            ),
          )
          as String);

  @override
  void clearCachedApi() => super.noSuchMethod(
    Invocation.method(#clearCachedApi, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<List<dynamic>>?> getSheet(String? sheetName) =>
      (super.noSuchMethod(
            Invocation.method(#getSheet, [sheetName]),
            returnValue: _i5.Future<List<List<dynamic>>?>.value(),
          )
          as _i5.Future<List<List<dynamic>>?>);

  @override
  _i5.Future<int?> findExpenseRowIndex(String? sheetName, String? recordID) =>
      (super.noSuchMethod(
            Invocation.method(#findExpenseRowIndex, [sheetName, recordID]),
            returnValue: _i5.Future<int?>.value(),
          )
          as _i5.Future<int?>);

  @override
  _i5.Future<void> updateExpense(
    String? sheetName,
    _i6.ExpenseRecord? expense,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateExpense, [sheetName, expense]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteExpense(String? sheetName, String? recordID) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpense, [sheetName, recordID]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> sheetExists(String? sheetName) =>
      (super.noSuchMethod(
            Invocation.method(#sheetExists, [sheetName]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<String>> getAllSheetNames() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSheetNames, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<bool> isCategoryUsed(
    String? categoryId,
    List<String>? allSheetNames,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isCategoryUsed, [categoryId, allSheetNames]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> updateExpensesCategory(
    String? oldCategoryId,
    String? newCategoryId,
    List<String>? allSheetNames,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateExpensesCategory, [
              oldCategoryId,
              newCategoryId,
              allSheetNames,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int?> getSheetId(String? sheetName) =>
      (super.noSuchMethod(
            Invocation.method(#getSheetId, [sheetName]),
            returnValue: _i5.Future<int?>.value(),
          )
          as _i5.Future<int?>);

  @override
  _i5.Future<void> batchUpdate(List<_i2.Request>? requests) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdate, [requests]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addExpense(
    String? sheetName,
    _i6.ExpenseRecord? testExpense,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addExpense, [sheetName, testExpense]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> createSheet(String? sheetName) =>
      (super.noSuchMethod(
            Invocation.method(#createSheet, [sheetName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteRow(int? sheetId, int? rowIndex) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRow, [sheetId, rowIndex]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateRow(
    String? sheetName,
    int? rowIndex,
    List<dynamic>? values,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRow, [sheetName, rowIndex, values]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> appendSheet(
    String? sheetName,
    List<List<dynamic>>? values,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#appendSheet, [sheetName, values]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateSheet(String? range, List<List<dynamic>>? values) =>
      (super.noSuchMethod(
            Invocation.method(#updateSheet, [range, values]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SheetsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetsApi extends _i1.Mock implements _i2.SheetsApi {
  MockSheetsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SpreadsheetsResource get spreadsheets =>
      (super.noSuchMethod(
            Invocation.getter(#spreadsheets),
            returnValue: _FakeSpreadsheetsResource_0(
              this,
              Invocation.getter(#spreadsheets),
            ),
          )
          as _i2.SpreadsheetsResource);
}

/// A class which mocks [SpreadsheetsResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpreadsheetsResource extends _i1.Mock
    implements _i2.SpreadsheetsResource {
  MockSpreadsheetsResource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SpreadsheetsDeveloperMetadataResource get developerMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#developerMetadata),
            returnValue: _FakeSpreadsheetsDeveloperMetadataResource_1(
              this,
              Invocation.getter(#developerMetadata),
            ),
          )
          as _i2.SpreadsheetsDeveloperMetadataResource);

  @override
  _i2.SpreadsheetsSheetsResource get sheets =>
      (super.noSuchMethod(
            Invocation.getter(#sheets),
            returnValue: _FakeSpreadsheetsSheetsResource_2(
              this,
              Invocation.getter(#sheets),
            ),
          )
          as _i2.SpreadsheetsSheetsResource);

  @override
  _i2.SpreadsheetsValuesResource get values =>
      (super.noSuchMethod(
            Invocation.getter(#values),
            returnValue: _FakeSpreadsheetsValuesResource_3(
              this,
              Invocation.getter(#values),
            ),
          )
          as _i2.SpreadsheetsValuesResource);

  @override
  _i5.Future<_i2.BatchUpdateSpreadsheetResponse> batchUpdate(
    _i2.BatchUpdateSpreadsheetRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #batchUpdate,
              [request, spreadsheetId],
              {#$fields: $fields},
            ),
            returnValue: _i5.Future<_i2.BatchUpdateSpreadsheetResponse>.value(
              _FakeBatchUpdateSpreadsheetResponse_4(
                this,
                Invocation.method(
                  #batchUpdate,
                  [request, spreadsheetId],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.BatchUpdateSpreadsheetResponse>);

  @override
  _i5.Future<_i2.Spreadsheet> create(
    _i2.Spreadsheet? request, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [request], {#$fields: $fields}),
            returnValue: _i5.Future<_i2.Spreadsheet>.value(
              _FakeSpreadsheet_5(
                this,
                Invocation.method(#create, [request], {#$fields: $fields}),
              ),
            ),
          )
          as _i5.Future<_i2.Spreadsheet>);

  @override
  _i5.Future<_i2.Spreadsheet> get(
    String? spreadsheetId, {
    bool? includeGridData,
    List<String>? ranges,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [spreadsheetId],
              {
                #includeGridData: includeGridData,
                #ranges: ranges,
                #$fields: $fields,
              },
            ),
            returnValue: _i5.Future<_i2.Spreadsheet>.value(
              _FakeSpreadsheet_5(
                this,
                Invocation.method(
                  #get,
                  [spreadsheetId],
                  {
                    #includeGridData: includeGridData,
                    #ranges: ranges,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Spreadsheet>);

  @override
  _i5.Future<_i2.Spreadsheet> getByDataFilter(
    _i2.GetSpreadsheetByDataFilterRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getByDataFilter,
              [request, spreadsheetId],
              {#$fields: $fields},
            ),
            returnValue: _i5.Future<_i2.Spreadsheet>.value(
              _FakeSpreadsheet_5(
                this,
                Invocation.method(
                  #getByDataFilter,
                  [request, spreadsheetId],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Spreadsheet>);
}

/// A class which mocks [SpreadsheetsValuesResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpreadsheetsValuesResource extends _i1.Mock
    implements _i2.SpreadsheetsValuesResource {
  MockSpreadsheetsValuesResource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AppendValuesResponse> append(
    _i2.ValueRange? request,
    String? spreadsheetId,
    String? range, {
    bool? includeValuesInResponse,
    String? insertDataOption,
    String? responseDateTimeRenderOption,
    String? responseValueRenderOption,
    String? valueInputOption,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #append,
              [request, spreadsheetId, range],
              {
                #includeValuesInResponse: includeValuesInResponse,
                #insertDataOption: insertDataOption,
                #responseDateTimeRenderOption: responseDateTimeRenderOption,
                #responseValueRenderOption: responseValueRenderOption,
                #valueInputOption: valueInputOption,
                #$fields: $fields,
              },
            ),
            returnValue: _i5.Future<_i2.AppendValuesResponse>.value(
              _FakeAppendValuesResponse_6(
                this,
                Invocation.method(
                  #append,
                  [request, spreadsheetId, range],
                  {
                    #includeValuesInResponse: includeValuesInResponse,
                    #insertDataOption: insertDataOption,
                    #responseDateTimeRenderOption: responseDateTimeRenderOption,
                    #responseValueRenderOption: responseValueRenderOption,
                    #valueInputOption: valueInputOption,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.AppendValuesResponse>);

  @override
  _i5.Future<_i2.BatchClearValuesResponse> batchClear(
    _i2.BatchClearValuesRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #batchClear,
              [request, spreadsheetId],
              {#$fields: $fields},
            ),
            returnValue: _i5.Future<_i2.BatchClearValuesResponse>.value(
              _FakeBatchClearValuesResponse_7(
                this,
                Invocation.method(
                  #batchClear,
                  [request, spreadsheetId],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.BatchClearValuesResponse>);

  @override
  _i5.Future<_i2.BatchClearValuesByDataFilterResponse> batchClearByDataFilter(
    _i2.BatchClearValuesByDataFilterRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #batchClearByDataFilter,
              [request, spreadsheetId],
              {#$fields: $fields},
            ),
            returnValue:
                _i5.Future<_i2.BatchClearValuesByDataFilterResponse>.value(
                  _FakeBatchClearValuesByDataFilterResponse_8(
                    this,
                    Invocation.method(
                      #batchClearByDataFilter,
                      [request, spreadsheetId],
                      {#$fields: $fields},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.BatchClearValuesByDataFilterResponse>);

  @override
  _i5.Future<_i2.BatchGetValuesResponse> batchGet(
    String? spreadsheetId, {
    String? dateTimeRenderOption,
    String? majorDimension,
    List<String>? ranges,
    String? valueRenderOption,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #batchGet,
              [spreadsheetId],
              {
                #dateTimeRenderOption: dateTimeRenderOption,
                #majorDimension: majorDimension,
                #ranges: ranges,
                #valueRenderOption: valueRenderOption,
                #$fields: $fields,
              },
            ),
            returnValue: _i5.Future<_i2.BatchGetValuesResponse>.value(
              _FakeBatchGetValuesResponse_9(
                this,
                Invocation.method(
                  #batchGet,
                  [spreadsheetId],
                  {
                    #dateTimeRenderOption: dateTimeRenderOption,
                    #majorDimension: majorDimension,
                    #ranges: ranges,
                    #valueRenderOption: valueRenderOption,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.BatchGetValuesResponse>);

  @override
  _i5.Future<_i2.BatchGetValuesByDataFilterResponse> batchGetByDataFilter(
    _i2.BatchGetValuesByDataFilterRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #batchGetByDataFilter,
              [request, spreadsheetId],
              {#$fields: $fields},
            ),
            returnValue:
                _i5.Future<_i2.BatchGetValuesByDataFilterResponse>.value(
                  _FakeBatchGetValuesByDataFilterResponse_10(
                    this,
                    Invocation.method(
                      #batchGetByDataFilter,
                      [request, spreadsheetId],
                      {#$fields: $fields},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.BatchGetValuesByDataFilterResponse>);

  @override
  _i5.Future<_i2.BatchUpdateValuesResponse> batchUpdate(
    _i2.BatchUpdateValuesRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #batchUpdate,
              [request, spreadsheetId],
              {#$fields: $fields},
            ),
            returnValue: _i5.Future<_i2.BatchUpdateValuesResponse>.value(
              _FakeBatchUpdateValuesResponse_11(
                this,
                Invocation.method(
                  #batchUpdate,
                  [request, spreadsheetId],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.BatchUpdateValuesResponse>);

  @override
  _i5.Future<_i2.BatchUpdateValuesByDataFilterResponse> batchUpdateByDataFilter(
    _i2.BatchUpdateValuesByDataFilterRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #batchUpdateByDataFilter,
              [request, spreadsheetId],
              {#$fields: $fields},
            ),
            returnValue:
                _i5.Future<_i2.BatchUpdateValuesByDataFilterResponse>.value(
                  _FakeBatchUpdateValuesByDataFilterResponse_12(
                    this,
                    Invocation.method(
                      #batchUpdateByDataFilter,
                      [request, spreadsheetId],
                      {#$fields: $fields},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.BatchUpdateValuesByDataFilterResponse>);

  @override
  _i5.Future<_i2.ClearValuesResponse> clear(
    _i7.$Empty? request,
    String? spreadsheetId,
    String? range, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #clear,
              [request, spreadsheetId, range],
              {#$fields: $fields},
            ),
            returnValue: _i5.Future<_i2.ClearValuesResponse>.value(
              _FakeClearValuesResponse_13(
                this,
                Invocation.method(
                  #clear,
                  [request, spreadsheetId, range],
                  {#$fields: $fields},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ClearValuesResponse>);

  @override
  _i5.Future<_i2.ValueRange> get(
    String? spreadsheetId,
    String? range, {
    String? dateTimeRenderOption,
    String? majorDimension,
    String? valueRenderOption,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [spreadsheetId, range],
              {
                #dateTimeRenderOption: dateTimeRenderOption,
                #majorDimension: majorDimension,
                #valueRenderOption: valueRenderOption,
                #$fields: $fields,
              },
            ),
            returnValue: _i5.Future<_i2.ValueRange>.value(
              _FakeValueRange_14(
                this,
                Invocation.method(
                  #get,
                  [spreadsheetId, range],
                  {
                    #dateTimeRenderOption: dateTimeRenderOption,
                    #majorDimension: majorDimension,
                    #valueRenderOption: valueRenderOption,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ValueRange>);

  @override
  _i5.Future<_i2.UpdateValuesResponse> update(
    _i2.ValueRange? request,
    String? spreadsheetId,
    String? range, {
    bool? includeValuesInResponse,
    String? responseDateTimeRenderOption,
    String? responseValueRenderOption,
    String? valueInputOption,
    String? $fields,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #update,
              [request, spreadsheetId, range],
              {
                #includeValuesInResponse: includeValuesInResponse,
                #responseDateTimeRenderOption: responseDateTimeRenderOption,
                #responseValueRenderOption: responseValueRenderOption,
                #valueInputOption: valueInputOption,
                #$fields: $fields,
              },
            ),
            returnValue: _i5.Future<_i2.UpdateValuesResponse>.value(
              _FakeUpdateValuesResponse_15(
                this,
                Invocation.method(
                  #update,
                  [request, spreadsheetId, range],
                  {
                    #includeValuesInResponse: includeValuesInResponse,
                    #responseDateTimeRenderOption: responseDateTimeRenderOption,
                    #responseValueRenderOption: responseValueRenderOption,
                    #valueInputOption: valueInputOption,
                    #$fields: $fields,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.UpdateValuesResponse>);
}
