version: "3.8"

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_management_db
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/user_management_db
      SECRET_KEY: super-secret-key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      - db

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app  # Add this line
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/test_user_management_db
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
    depends_on:
      - db

volumes:
  postgres_data:

